version: '3.8'

services:
  db:
    image: postgres:14.7-alpine3.17
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

volumes:
  postgres-data:
    driver: local
