name: CI

env:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-latest

    container: node:18

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: 🧪 Run test
        run: pnpm run test

      - name: 🔬 Lint file content
        run: pnpm run lint

      - name: 💪 Check types
        run: pnpm run typecheck
